/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrandsBrandIdRouteImport } from './routes/brands.$brandId'
import { Route as AdvertsAdvertIdRouteImport } from './routes/adverts.$advertId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsBrandIdRoute = BrandsBrandIdRouteImport.update({
  id: '/brands/$brandId',
  path: '/brands/$brandId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertsAdvertIdRoute = AdvertsAdvertIdRouteImport.update({
  id: '/adverts/$advertId',
  path: '/adverts/$advertId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adverts/$advertId': typeof AdvertsAdvertIdRoute
  '/brands/$brandId': typeof BrandsBrandIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adverts/$advertId': typeof AdvertsAdvertIdRoute
  '/brands/$brandId': typeof BrandsBrandIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adverts/$advertId': typeof AdvertsAdvertIdRoute
  '/brands/$brandId': typeof BrandsBrandIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/adverts/$advertId' | '/brands/$brandId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/adverts/$advertId' | '/brands/$brandId'
  id: '__root__' | '/' | '/adverts/$advertId' | '/brands/$brandId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvertsAdvertIdRoute: typeof AdvertsAdvertIdRoute
  BrandsBrandIdRoute: typeof BrandsBrandIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/$brandId': {
      id: '/brands/$brandId'
      path: '/brands/$brandId'
      fullPath: '/brands/$brandId'
      preLoaderRoute: typeof BrandsBrandIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adverts/$advertId': {
      id: '/adverts/$advertId'
      path: '/adverts/$advertId'
      fullPath: '/adverts/$advertId'
      preLoaderRoute: typeof AdvertsAdvertIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvertsAdvertIdRoute: AdvertsAdvertIdRoute,
  BrandsBrandIdRoute: BrandsBrandIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
